export const PROJECT_DEFS = {
  PARTY_HQ: {
    name: "🏢 Party Headquarters",
    cost: "💰 100, ✊ 20",
    costCoins: 100,
    costMorale: 20,
    costCorruption: 0,
    costMedia: 0,
    costSupport: 0,
    yield: "💰 +12, 📢 +3 per turn",
    offensive: false,
  },
  IT_CELL: {
    name: "💻 IT Cell (Digital Bureau)",
    cost: "💰 60, ⚖️ 10",
    costCoins: 60,
    costMorale: 0,
    costCorruption: 10,
    costMedia: 0,
    costSupport: 0,
    yield: "📢 +2, 📈 +1% per turn",
    offensive: false,
  },
  CADRE_OFFICE: {
    name: "🏘️ District Cadre Offices",
    cost: "💰 50, ✊ 30",
    costCoins: 50,
    costMorale: 30,
    costCorruption: 0,
    costMedia: 0,
    costSupport: 0,
    yield: "✊ +4, 📈 +1% per turn",
    offensive: false,
  },
  THINK_TANK: {
    name: "🧠 Policy Research Think Tank",
    cost: "💰 40, ✊ 10",
    costCoins: 40,
    costMorale: 10,
    costCorruption: 0,
    costMedia: 0,
    costSupport: 0,
    yield: "💰 +2, 📢 +4 per turn",
    offensive: false,
  },
  TRAINING_ACADEMY: {
    name: "🏫 Grassroots Training Academy",
    cost: "💰 45, ✊ 20",
    costCoins: 45,
    costMorale: 20,
    costCorruption: 0,
    costMedia: 0,
    costSupport: 0,
    yield: "✊ +5 per turn",
    offensive: false,
  },
  YOUTH_WING: {
    name: "✊ Youth Wing Network",
    cost: "💰 35, ✊ 15",
    costCoins: 35,
    costMorale: 15,
    costCorruption: 0,
    costMedia: 0,
    costSupport: 0,
    yield: "✊ +3, 📈 +1% per turn",
    offensive: false,
  },
  MEGA_RALLY: {
    name: "📢 Mega Rally",
    cost: "💰 60, 📢 10, 📈 5%",
    costCoins: 60,
    costMorale: 0,
    costCorruption: 0,
    costMedia: 10,
    costSupport: 5,
    yield: "💰 +6, 📢 +1, 📈 +1% per turn",
    offensive: false,
  },
  PRIME_LEADER_VISIT: {
    name: "⭐ Prime Leader Visit",
    cost: "💰 100, ⚖️ 10, 📢 10",
    costCoins: 100,
    costMorale: 0,
    costCorruption: 10,
    costMedia: 10,
    costSupport: 0,
    yield: "💰 +10, ⚖️ -1, 📢 +1, 📈 +2% per turn",
    offensive: false,
  },
  FOUNDATION_DAY: {
    name: "🎉 Foundation Day Celebration",
    cost: "💰 40, ✊ 15",
    costCoins: 40,
    costMorale: 15,
    costCorruption: 0,
    costMedia: 0,
    costSupport: 0,
    yield: "💰 +4, ✊ +2, 📈 +1% per turn",
    offensive: false,
  },
  PARTY_CONGRESS: {
    name: "🤝 Party Congress",
    cost: "💰 120, 📢 20, 📈 10%",
    costCoins: 120,
    costMorale: 0,
    costCorruption: 0,
    costMedia: 20,
    costSupport: 10,
    yield: "💰 +12, 📢 +2, 📈 +1%, ✊ +2 per turn",
    offensive: false,
  },
  DISSENT_NEWSPAPER: {
    name: "📰 Dissenting Newspaper",
    cost: "💰 65, ✊ 15",
    costCoins: 65,
    costMorale: 15,
    costCorruption: 0,
    costMedia: 0,
    costSupport: 0,
    yield: "💥 📈 -1% to Target per turn",
    offensive: true,
  },
  MEDIA_HOUSE: {
    name: "📺 Hostile Media House",
    cost: "💰 55, ⚖️ 10",
    costCoins: 55,
    costMorale: 0,
    costCorruption: 10,
    costMedia: 0,
    costSupport: 0,
    yield: "💥 📢 -4 to Target per turn",
    offensive: true,
  },
  PARTY_DISSENT: {
    name: "📣 Encourage Rank Dissent",
    cost: "💰 45, ✊ 25",
    costCoins: 45,
    costMorale: 25,
    costCorruption: 0,
    costMedia: 0,
    costSupport: 0,
    yield: "💥 ✊ -3 to Target per turn",
    offensive: true,
  },
  CORRUPTION_EXPOSE: {
    name: "🔍 Expose Corruption Center",
    cost: "💰 40, ⚖️ 5",
    costCoins: 40,
    costMorale: 0,
    costCorruption: 5,
    costMedia: 0,
    costSupport: 0,
    yield: "💥 ⚖️ +3 to Target per turn",
    offensive: true,
  },
  CAMPAIGN_SABOTAGE: {
    name: "💣 Campaign Sabotage",
    cost: "💰 50, 📢 10",
    costCoins: 50,
    costMorale: 0,
    costCorruption: 0,
    costMedia: 10,
    costSupport: 0,
    yield: "💥 💰 -5, 📢 -1, ✊ -2 to Target per turn",
    offensive: true,
  },
  AUDIT_HARASSMENT: {
    name: "💼 Audit Harassment",
    cost: "💰 80, ⚖️ 10",
    costCoins: 80,
    costMorale: 0,
    costCorruption: 10,
    costMedia: 0,
    costSupport: 0,
    yield: "💥 💰 -8, ✊ -1, ⚖️ +1 to Target per turn",
    offensive: true,
  },
  MEDIA_SMEAR: {
    name: "📻 Media Smear Campaign",
    cost: "💰 60, ⚖️ 10",
    costCoins: 60,
    costMorale: 0,
    costCorruption: 10,
    costMedia: 0,
    costSupport: 0,
    yield: "💥 💰 -6, 📢 -2, 📈 -1% to Target per turn",
    offensive: true,
  },
  WHISTLEBLOWER_FORUM: {
    name: "🔍 Whistleblower Forum",
    cost: "💰 50, 📢 10",
    costCoins: 50,
    costMorale: 0,
    costCorruption: 0,
    costMedia: 10,
    costSupport: 0,
    yield: "✊ +2, ⚖️ -6 per turn",
    offensive: false,
  },
  CITIZEN_OUTREACH: {
    name: "🤝 Citizen Outreach Program",
    cost: "💰 40, ✊ 5",
    costCoins: 40,
    costMorale: 5,
    costCorruption: 0,
    costMedia: 0,
    costSupport: 0,
    yield: "⚖️ -1, 📢 +3, 📈 +1% per turn",
    offensive: false,
  },
  PROTEST_STRIKE: {
    name: "✊ Organize Protest Strike",
    cost: "💰 70, ✊ 10",
    costCoins: 70,
    costMorale: 10,
    costCorruption: 0,
    costMedia: 0,
    costSupport: 0,
    yield: "💥 💰 -6, ✊ -4, 📈 -2% to Target per turn",
    offensive: true,
  },
  LEAK_INTERNAL_MEMO: {
    name: "📄 Leak Internal Memo",
    cost: "💰 55, 📢 5",
    costCoins: 55,
    costMorale: 0,
    costCorruption: 0,
    costMedia: 5,
    costSupport: 0,
    yield: "💥 ✊ -3, ⚖️ +3, 📈 -1% to Target per turn",
    offensive: true,
  }
};
