export const PROJECT_DEFS = {
  PARTY_HQ: {
    name: "🏢 Party Headquarters",
    cost: "100 Coins, 20 Morale",
    costCoins: 100,
    costMorale: 20,
    costCorruption: 0,
    costMedia: 0,
    costSupport: 0,
    yield: "💰 +12 Coins, 📢 +3 Media Image per turn",
    offensive: false,
  },
  IT_CELL: {
    name: "💻 IT Cell (Digital Bureau)",
    cost: "60 Coins, 10 Corruption",
    costCoins: 60,
    costMorale: 0,
    costCorruption: 10,
    costMedia: 0,
    costSupport: 0,
    yield: "📢 +2 Media Image, 📈 +1% Public Support per turn (from undecided)",
    offensive: false,
  },
  CADRE_OFFICE: {
    name: "🏘️ District Cadre Offices",
    cost: "50 Coins, 30 Morale",
    costCoins: 50,
    costMorale: 30,
    costCorruption: 0,
    costMedia: 0,
    costSupport: 0,
    yield: "⚡ +4 Morale, 📈 +1% Public Support per turn (from undecided)",
    offensive: false,
  },
  THINK_TANK: {
    name: "🧠 Policy Research Think Tank",
    cost: "40 Coins, 10 Morale",
    costCoins: 40,
    costMorale: 10,
    costCorruption: 0,
    costMedia: 0,
    costSupport: 0,
    yield: "💰 +2 Coins, 📢 +4 Media Image per turn",
    offensive: false,
  },
  TRAINING_ACADEMY: {
    name: "🏫 Grassroots Training Academy",
    cost: "45 Coins, 20 Morale",
    costCoins: 45,
    costMorale: 20,
    costCorruption: 0,
    costMedia: 0,
    costSupport: 0,
    yield: "⚡ +5 Morale per turn",
    offensive: false,
  },
  YOUTH_WING: {
    name: "✊ Youth Wing Network",
    cost: "35 Coins, 15 Morale",
    costCoins: 35,
    costMorale: 15,
    costCorruption: 0,
    costMedia: 0,
    costSupport: 0,
    yield: "⚡ +3 Morale, 📈 +1% Public Support per turn (from undecided)",
    offensive: false,
  },
  MEGA_RALLY: {
    name: "📢 Mega Rally",
    cost: "60 Coins, 10 Media Image, 5% Support",
    costCoins: 60,
    costMorale: 0,
    costCorruption: 0,
    costMedia: 10,
    costSupport: 5,
    yield: "💰 +6 Coins, 📢 +1 Media Image, 📈 +1% Public Support per turn (from undecided)",
    offensive: false,
  },
  PRIME_LEADER_VISIT: {
    name: "⭐ Prime Leader Visit",
    cost: "100 Coins, 10 Corruption, 10 Media Image",
    costCoins: 100,
    costMorale: 0,
    costCorruption: 10,
    costMedia: 10,
    costSupport: 0,
    yield: "💰 +10 Coins, ⚖️ -1 Corruption, 📢 +1 Media Image, 📈 +2% Public Support per turn (from undecided)",
    offensive: false,
  },
  FOUNDATION_DAY: {
    name: "🎉 Foundation Day Celebration",
    cost: "40 Coins, 15 Morale",
    costCoins: 40,
    costMorale: 15,
    costCorruption: 0,
    costMedia: 0,
    costSupport: 0,
    yield: "💰 +4 Coins, ✊ +2 Morale, 📈 +1% Public Support per turn (from undecided)",
    offensive: false,
  },
  PARTY_CONGRESS: {
    name: "🤝 Party Congress",
    cost: "120 Coins, 20 Media Image, 10% Support",
    costCoins: 120,
    costMorale: 0,
    costCorruption: 0,
    costMedia: 20,
    costSupport: 10,
    yield: "💰 +12 Coins, 📢 +2 Media Image, 📈 +1% Public Support, ✊ +2 Morale per turn (from undecided)",
    offensive: false,
  },
  DISSENT_NEWSPAPER: {
    name: "📰 Dissenting Newspaper",
    cost: "65 Coins, 15 Morale",
    costCoins: 65,
    costMorale: 15,
    costCorruption: 0,
    costMedia: 0,
    costSupport: 0,
    yield: "💥 -1% Public Support from Target (transfers to Undecided)",
    offensive: true,
  },
  MEDIA_HOUSE: {
    name: "📺 Hostile Media House",
    cost: "55 Coins, 10 Corruption",
    costCoins: 55,
    costMorale: 0,
    costCorruption: 10,
    costMedia: 0,
    costSupport: 0,
    yield: "💥 -4 Media Image to Target per turn",
    offensive: true,
  },
  PARTY_DISSENT: {
    name: "📣 Encourage Rank Dissent",
    cost: "45 Coins, 25 Morale",
    costCoins: 45,
    costMorale: 25,
    costCorruption: 0,
    costMedia: 0,
    costSupport: 0,
    yield: "💥 -3 Morale to Target per turn",
    offensive: true,
  },
  CORRUPTION_EXPOSE: {
    name: "🔍 Expose Corruption Center",
    cost: "40 Coins, 5 Corruption",
    costCoins: 40,
    costMorale: 0,
    costCorruption: 5,
    costMedia: 0,
    costSupport: 0,
    yield: "💥 +3 Corruption to Target per turn",
    offensive: true,
  },
  CAMPAIGN_SABOTAGE: {
    name: "💣 Campaign Sabotage",
    cost: "50 Coins, 10 Media Image",
    costCoins: 50,
    costMorale: 0,
    costCorruption: 0,
    costMedia: 10,
    costSupport: 0,
    yield: "💥 -5 Coins, -1 Media Image, -2 Morale to Target per turn",
    offensive: true,
  },
  AUDIT_HARASSMENT: {
    name: "💼 Audit Harassment",
    cost: "80 Coins, 10 Corruption",
    costCoins: 80,
    costMorale: 0,
    costCorruption: 10,
    costMedia: 0,
    costSupport: 0,
    yield: "💥 -8 Coins, -1 Morale, +1 Corruption to Target per turn",
    offensive: true,
  },
  MEDIA_SMEAR: {
    name: "📻 Media Smear Campaign",
    cost: "60 Coins, 10 Corruption",
    costCoins: 60,
    costMorale: 0,
    costCorruption: 10,
    costMedia: 0,
    costSupport: 0,
    yield: "💥 -6 Coins, -2 Media Image, -1% Public Support to Target per turn",
    offensive: true,
  },
  WHISTLEBLOWER_FORUM: {
    name: "🔍 Whistleblower Forum",
    cost: "50 Coins, 10 Media Image",
    costCoins: 50,
    costMorale: 0,
    costCorruption: 0,
    costMedia: 10,
    costSupport: 0,
    yield: "✊ +2 Morale, ⚖️ -6 Corruption per turn",
    offensive: false,
  },
  CITIZEN_OUTREACH: {
    name: "🤝 Citizen Outreach Program",
    cost: "40 Coins, 5 Morale",
    costCoins: 40,
    costMorale: 5,
    costCorruption: 0,
    costMedia: 0,
    costSupport: 0,
    yield: "⚖️ -1 Corruption, 📢 +3 Media Image, 📈 +1% Public Support per turn (from undecided)",
    offensive: false,
  },
  PROTEST_STRIKE: {
    name: "✊ Organize Protest Strike",
    cost: "70 Coins, 10 Morale",
    costCoins: 70,
    costMorale: 10,
    costCorruption: 0,
    costMedia: 0,
    costSupport: 0,
    yield: "💥 -6 Coins, -4 Morale, -2% Public Support to Target per turn",
    offensive: true,
  },
  LEAK_INTERNAL_MEMO: {
    name: "📄 Leak Internal Memo",
    cost: "55 Coins, 5 Media Image",
    costCoins: 55,
    costMorale: 0,
    costCorruption: 0,
    costMedia: 5,
    costSupport: 0,
    yield: "💥 -3 Morale, +3 Corruption, -1% Public Support to Target per turn",
    offensive: true,
  }
};

